### ISSUE TITLE
Switch from grunt to gulp

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/design-system#116]
The dev team is using gulp elsewhere and so are the Standards so our design system is now the orphan on grunt. Time to switch.

**Comment by humancompanion** [comment]
From Dano, lead on USWDS:

> Hey all — Since USWDS 2.0 Beta (and 1.x as well, to be honest) is more useful when you customize its settings and compile your project CSS from source Sass, we've been working to try and make it simpler to incorporate a Gulp-based workflow on USWDS projects. To that end, I want to show you all a new project we've just added to our repos: `uswds-gulp`: https://github.com/uswds/uswds-gulp
> 
> `uswds-gulp` is a way to initialize a USWDS project and set up an automated process for compiling USWDS Sass. So if you're interested, please take a look at the repo, read the description and instructions in the `Readme`, and let us know (either here or as an issue in the `uswds-gulp` repo) what we can do to make it better.
> 
> We've also updated the general USWDS installation guidance at https://v2.designsystem.digital.gov/documentation/developers/ to reflect the changes in USWDS 2.0 Beta.

This would be a good place for us to start.

**Comment by dreeeeewwwww** [comment]
Solid! I'll start reading through their instructions.

**Comment by humancompanion** [comment]
I wish I had looked at this issue again so I would have seen my comment to check out uswds-gulp. Regardless, I updated our gulpfile.js based on their v2 gulpfile. 

I had to make a few changes:

#### CSS
* Having multiple src files with different naming conventions and targets was ill-advised, a hassle, and is no more. 
  * I'd like to perhaps drop the usajobs-design-system- prefix as well but, to keep most of it consistent with what is their now I kept that.
* RENAMES:
  * usajobs-design-system-base.css is now usajobs-design-system-all.css.  
  * I also dropped the BEM-like '--' in css filenames for help center and open opps. 
*. _layouts/*.scss files now just build into css/. No more layouts sub-directory.
  * It would have required handling them differently and it just seemed unnecessary given how few layout files we use in the design system (they still make sense in prototype repos).

#### JS
* Browserify and Babel and no longer happy with our antiquated jquery JS. Thus I just decided to concat the components.js to a distinct file and compile the USWDS JS into a new file: uswds-components.js
* We should get off of jshint and onto es-lint. I'll tackle that soon.
  
### New additions
I need to test all of this out more but, once I fix up all of the css paths that changed we should have:

* Use of browsersync
* No rebuilding of jekyll when only scss or js has changed
* Less errors related to node-sass
* Deployment via npm scripts using gulp-gh-pages

We'll definitely need to warn the dev team about all of the CSS filename changes and use semvar to indicate this would be a breaking release. 

Once @dreeeeewwwww and I can review this tomorrow I'm going to move onto getting us to v2 of the Standards.

**Comment by dreeeeewwwww** [comment]
@humancompanion gulp tasks are working ok for me! But ... with two exceptions:

<img width="1419" alt="screen shot 2019-01-16 at 4 50 20 pm" src="https://user-images.githubusercontent.com/13023132/51280882-dcbeb380-19ae-11e9-87c6-92cca2435aef.png">
- [ ] `gulp default` - everything seems to run, but watched local server doesn't have CSS

<img width="890" alt="screen shot 2019-01-16 at 4 54 18 pm" src="https://user-images.githubusercontent.com/13023132/51281101-74240680-19af-11e9-935c-51a6360807fc.png">
- [ ] `gulp buildcssfromsass` - errors out `File not found with singular glob`

**Comment by humancompanion** [comment]
Last task is to consume the design-system in Help and to do that requires a new npm package. Also, need to warn the dev team about the name changes.
