### ISSUE TITLE
USAJOBS Design Template Component Bugs

### ISSUE THREAD

**Issue by sean-lewis** [USAJOBS/design-system#129]
Both the [JOA Intro](http://usajobs.github.io/design-system/joa-intro/) and [Agency Contact](http://usajobs.github.io/design-system/joa-agency-contact/) pages have erratic formatting. Cause is unclear.

**Comment by humancompanion** [comment]
Two different issues: 

* [ ] Read more plugin seems to not be loading or doing it's job to hide the content in the Agency contact component.
* [ ] JOA intro - The aside is somehow outside the normal flow of the page which is causing it's length to not be accommodated.
