### ISSUE TITLE
Components: Logo Usage

### ISSUE THREAD

**Issue by dgarber** [USAJOBS/design-system#13]
This tracks the work to create the Logo and Logo usage component of the design system.
![usajobs-logo_for web](https://cloud.githubusercontent.com/assets/2085500/10665878/2e3eafc4-789c-11e5-85ff-3c8ede4da3da.png)
![usajobs-logo_for web_small](https://cloud.githubusercontent.com/assets/2085500/10665888/37666d62-789c-11e5-8b6b-ba91ec5f0a7b.png)

**Comment by humancompanion** [comment]
@dgarber - Do you have the original vector assets (.ai or svg files) for the logo?

**Comment by humancompanion** [comment]
After our discussion in the Product Owners meeting last Wednesday I suspect that this is the logo we want to use:

![usajobs_logo](https://cloud.githubusercontent.com/assets/352987/11751138/94db599a-a005-11e5-8010-b30f3baf4bb5.png)

@dgarber - Is that your understanding as well?
