### ISSUE TITLE
Footer: Clicking on sub-section titles causes items to disappear at $M breakpoint (600px)

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/design-system#136]
This is a bug that has found its way out into production thus it is urgent. The sub-sections of the footer act as drawers below the $M breakpoint (600px). Above that breakpoint the sub-sections turn into a simple list with the title, the drawer face toggle, hiding the handle and just acting as a title. However, the titles are still clickable when they should not be. 

We can solve this in a number of ways however, I think the simplest fix is to simple override the following rule in CSS at the $M breakpoint. I'll even sanction the use of !important here is necessary.

```
.usa-footer-big ul.hidden li {
   display: none;
}
```

**Comment by starrchen** [comment]
Looking at this, having trouble getting this repo up and running to check fixes and will reach out to someone for help on that.

**Comment by humancompanion** [comment]
Done! Great job @starrchen!

**Comment by humancompanion** [comment]
@starrchen - Terrible code review on my part. In this case, you either updated the CSS directly or didn't commit the change to the footer.scss file. Either way, the change was blown away in the CSS when the sass was recompiled upon build.
