### ISSUE TITLE
Enable https for GitHub pages

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/design-system#141]
<img width="462" alt="screen shot 2018-10-09 at 3 12 55 pm" src="https://user-images.githubusercontent.com/13023132/46692717-fbeebd80-cbd5-11e8-9e2a-ebd7478beffc.png">

**Comment by humancompanion** [comment]
This URL works: https://usajobs.github.io/design-system/ It's just the github pages isn't redirecting from http to https. Looks like we can just turn on that enforcement: https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by humancompanion** [comment]
I followed the instructions below and turned it on for all of our github pages repos. Verified using http with the design-system that I was in fact redirected.
