### ISSUE TITLE
usajobs.gov strips leading zero in ZIP code search filter

### ISSUE THREAD

**Issue by anselmbradford** [USAJOBS/design-system#159]
**Type:** What kind of issue is this?

A bug.

**Timeline:** 12/9/18

-----

**Description:**

This is an issue with https://www.usajobs.gov/Search/, but I wasn't sure where to put it so hope here works!

To repeat:

1. Visit https://www.usajobs.gov/Search/
2. Enter a ZIP code (aside: should it be `zip` or `ZIP` in the placeholder text?) with a leading zero, such as "08904" and click "Search"
3. See that the leading zero gets stripped off the filter:

![screen shot 2018-12-09 at 12 14 41 pm](https://user-images.githubusercontent.com/704760/49700405-17614f00-fbac-11e8-9f6a-929a958f87bc.png)

**Comment by humancompanion** [comment]
Thanks for filing this. We've filed a ticket in TFS, which tracks our production code base. It's #35859. 

I'll leave this github issue open so we can notify you when it gets fixed.

**Comment by humancompanion** [comment]
The fix for this was deployed back on January 11th:
https://usajobs.github.io/ATP-Support/job-announcement-playbook/release-notes/
