### ISSUE TITLE
Make build and deploy process consistent with other repos

### ISSUE THREAD

**Issue by dreeeeewwwww** [USAJOBS/design-system#160]
Currently the build/deploy process involves working in `master` and pushing to `gh-pages`. Does it work ok? Yes ... _but_ ... it is inconsistent with how we build/deploy our other repos & Jekyll sites.

**Comment by humancompanion** [comment]
On the other hand, we've recently seen a problem with the way we deploy other repos whereby another developer accidentally made commits to gh-pages which caused the subtree push to fail. We *think* we have a way around this by splitting then forcing a push but, that too can be error prone (and is a bit of a pain point). 

An alternative would be to use a continuous integration tool like TravisCI or CircleCI to run a battery of tests and then deploy to gh-pages after those tests pass. Travis CI, which we currently use on Help, does have this capability: https://docs.travis-ci.com/user/deployment/pages/

Their docs do seem to indicate we could deploy the _site directory. Not clear to me whether it runs a build step and then pushes in which case it would alleviate our need to use --baseurl with jekyll locally (though there are other ways around that) or if it just pushes the files as you have committed them. I'm presuming the latter.

**Comment by humancompanion** [comment]
This is done. We now deploy design-system like the other repos.
