### ISSUE TITLE
JOA: USDS Pilot

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/design-system#167]
**Type:** Tracks changes related to an upcoming job announcement pilot.

**Timeline:** 03/08/19

-----

**Description:**

This issue will map the fields currently in the SIF to where they appear in the pilot. It will also track changes made related to the pilot.

-----

**To do:**

- [x] Map dynamic content to SIF fields in doi.json file.
- [x] Explore informational banner in How you will be evaluated

**Comment by humancompanion** [comment]
@jdstill and @ddescombes - Here is a breakdown of where all the values in the JOA pilot are coming from. Questions below. The summary is: I think it's possible to stick to the SIF.

### Map of fields by component

1. Banner: Stays the same - PositionTitle, DepartmentName, OrganizationName
2. Nav: Different static options
3. Summary: Stays the same but with new header and position - UserArea.Details.JobSummary 
4. Responsibilities: Stays the same but with new header - UserArea.Details.MajorDutiesList 
5. Qualifications: 
  * Initial paragraph: QualificationsSummary. 
  * Competency list: UserArea.Details.KeyRequirements 
  * Follow-up paragraph and list: UserArea.Details.OtherInformation.
6. This job is open to: Stays the same but in new position - UserArea.Details.HiringPath
7. Where you'll work:
  * Initial paragraph: AgencyMarketingStatement
  * Link: AgencyMarketingURL
  * Link text:  Learn more about careers at the {{ job.OrganizationName }}.
8. Benefits drawer: 
  * Text: Static content
  * Learn more about federal benefits link: Static content
  * Link URL: UserArea.Details.BenefitsURL
  * Link text:  Learn more about benefits at the {{ job.OrganizationName }}.
9. Contact the agency drawer:
  * Same as today's contact sub-section within How to apply sans the header, gray background, and "Learn more about this agency" link.
10. How you will be evaluated: Static content, including the modal. This is also specific to the pilot.
11. Required documents: Static content. We hope to make this dynamic at some point in the future beyond the pilot but for now this content will suffice.
12. Fair and transparent: Static content.
13. Overview: Same sources as today.
14. Locations: Same as today.
15. Get help link: Static content.
16. Numbers: Announcement and control numbers stay the same but appear in two positions at different breakpoints.

#### Open questions
* Agency contact information: I don't see it in the docs (https://developer.usajobs.gov/API-Reference/GET-api-Search) nor in the json output so I'm not sure where these fields live in the schema. I used the field names that I thought were correct from the last Data Dictionary I had (https://airtable.com/invite/l?inviteId=inv30UrKADk2V7ik6&inviteToken=410806f44e056f683e66aa2a4ffd7d87abbbcc5431a79ffb3ff67923085970f2)
* Qualifications
  * Each initial item in the list should be in bold. I'm not sure how that appears in the SIF when someone creating an announcement decides to send some bold text so I passed HTML.
  * There was no clear mapping for the paragraph that follows the competency list. I stuck it in OtherInformation.
  * I put HTML (a paragraph tag and unordered list) in OtherInformation. I believe we allow for these tags.
* BenefitsURL: I'm not sure if I have this in the right place in the schema.

**Comment by humancompanion** [comment]
USDS wants us to test this the week of 2/25.

**Comment by Piglady64** [comment]
I have reserved GSA for Wednesday February 27th from 11;00 to 1:30. We may not need all of this time but wanted to make sure we have time to set up and then take care of the stragglers at the end. I asked for 2 table with 3 chairs at each table (facilitator, observer, participant). I will get the WiFi username and password that morning before we go over.

**Comment by humancompanion** [comment]
### Items to address in UAT version
* The secondary menu plus doesn't appear at the ML breakpoint (768px). It needs to be updated to be a FontAwesome 5 icon (change the first ```.fa``` to ```.fas```).
* The border line to the left of that icon doesn't run from top to bottom. That may just be because the icon is missing.
* The bullets under Responsibilities have the class ```.usajobs-list-bullets``` however, the bullets under Qualifications do not. I'd prefer to have that class on both (it removes the indentation and thus saves some vertical height) but, if that's not possible I'd prefer to have it on neither so that all of the bullets are consistent. 
* The footer we're using in the pilot is a different more brief footer. It deliberately doesn't include our fat-footer navigation (jury is still out on this post-pilot for sure but for now I'm bending on this one). Note that there is no return to top in this variation of the footer either. I mention it because at desktop widths it prevents the right rail background color from reaching down to the footer.

### Changes made since hand-off
We ran a usability test yesterday and thus have a few small changes to request. If these can be accommodated, great. If not, we'll request them at a later date.

* We decided to switch the banner back to how it is today where the agency and department appear on distinct lines.
* The accordion drawers were not all of the same height in Required Documents so I set a min-height on them.
* I increased the margin between the bottom apply button bar and the Required Documents section.
* We added two warnings. The first in How you will be evaluated and the second in Required Documents. 
* Along with those warnings I removed the bullets in the All Applicants drawer of Required Documents and replaced it with a paragraph (this is because one of the bullets moved up into the warning).

NOTE: I made some CSS changes in issue #168 that were not impacting this JOA but do impact all other JOAs. Not sure if it's possible to pick up that change but, if possible it would be super cool because it makes bullets disappear in the JOA and it was all the fault of the design system all along.

**Comment by humancompanion** [comment]
This shipped last Friday.
