### ISSUE TITLE
Typography: Correct heading sizes

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/design-system#28]
I just noticed that the Standards define different header sizes for the Source Sans Pro headings and body pairing, which we are using. Those sizes are only defined in the styleguide.css file for the system itself and so I didn't notice them. Easy to fix but, we've got to communicate this immediately to the dev team. 

cc/ @PeterToohey

**Comment by PeterToohey** [comment]
Do we want to just update the global typography ticket or does this need to be added 5.3.1?

**Comment by humancompanion** [comment]
@PeterToohey - We can just update the ticket. Let's talk this afternoon and I can help you revise it. Thanks. Essentially, our headers were a bit too small. App Guide only uses h1-h3 so it was a simple, quick fix.

**Comment by PeterToohey** [comment]
@humancompanion Updated tickets and emailed Dev team.  I will update you if they have any questions.
