### ISSUE TITLE
Alerts: All alerts should be dismissible

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/design-system#45]
While we have our success alert demonstrating that an alert is dismissible I failed to extend that to the other alerts (probably because the US Standards don't include the ability to dismiss an alert and we started from their code). We should make our alerts uniform and thus add the ability to dismiss them.

**Comment by kyhryt** [comment]
This was an intentional design decision because we didn't want users accidentally dismissing our alerts and not being able to see them again. I'm all for adding the close feature for all of our alerts, just wanted to call this out :)

**Comment by humancompanion** [comment]
@kyhryt - I updated our guidelines to the following:

The Standards state: "Allow a user to dismiss a notification wherever appropriate." We believe it is appropriate to globally state that all alerts below the level of error should be dismissible. Errors should not be dismissible because they should only be present when the user cannot continue and/or is required to take action.
