### ISSUE TITLE
Component: Modals

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/design-system#6]
This issues tracks creating and documenting the modals we have introduced in Application Guide: Welcome and Confirm Deletion.

**Comment by humancompanion** [comment]
Comments from Ky from issue #9:

* [ ] Align modal body copy and header
* [ ] Change cancel button to link
* [ ] Use $color-gray-light on line dividers
* [ ] The header color should also be #112e51

Ky - The header is an h2. Are you asking for all h1 and h2 elements to be $color-primary-darkest (#112e51)? That's fine, just want to confirm your intent.

**Comment by humancompanion** [comment]
Just a note that, yes indeed, the desire was to make all h1 and h2 elements $color-primary-darkest which is now the case.

**Comment by humancompanion** [comment]
* [ ] @nathancurtis points out that the close circle is rather oblong. He is not wrong.
* [ ] Fix the backdrop to be an element distinct from the modal in order to hide it from assistive tech with aria-hidden="true".

**Comment by kyhryt** [comment]
I thought the circle was more of an oval shape :)

**Comment by humancompanion** [comment]
To be code complete I need to:
* [ ] Capture tab within the modal
* [ ] Investigate min and max widths & heights

**Comment by humancompanion** [comment]
Visual style updates:

* [ ] Move close button over the corner of the modal.
* [ ] Move the primary action button to the right.
* [ ] Make the cancel link a button and put it to the left of the primary action button.

**Comment by humancompanion** [comment]
* [ ] Add the modal alert.info variation.
