### ISSUE TITLE
Create node module for delivery of sass and or css and related assets 

### ISSUE THREAD

**Issue by lawrencek76** [USAJOBS/design-system#65]
To enable projects to more easily consume the css and related assets from this repository we need to produce a bower package or other similar package format (nuget, npm).

potential free CI services for building the package
https://www.appveyor.com/
https://travis-ci.org/
http://teamcity.codebetter.com/

**Comment by humancompanion** [comment]
18F has started packing the U.S. Design Standards as a node module and that is my preferred package as well:
https://github.com/18F/web-design-standards#using-npm

However, I've not started consuming the web design standards via the node module yet (this was a recent change). To do that I need to:

* [ ] Add web-design-standards as a dependent package in package.json
* [ ] Update Gruntfile.js to incorporate sass files in their new locations.
* [ ] Update sass to pull in _variables.scss and other important files from their new locations.

Once that is done I can move onto packaging our design system as a node module.

**Comment by humancompanion** [comment]
I created issues #80 and #81 for the remaining work related to this request. Closing.
