### ISSUE TITLE
Document: Delete is confusing users in application guide

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/design-system#72]
We've received complaints to Support that the delete link in the Document component in application guide is confusing. My suspicion is that users are not seeing the form indicator in the upper right-hand corner of the component and thus thinking that delete is going to remove the doc from their application package when in fact it removes the document from their account completely. 

It isn't necessary to be able to prune documents while applying. Thus the obvious answer is to remove the destructive action.

**Comment by kyhryt** [comment]
Modal attached for us to discussed. 

<img width="1440" alt="screen shot 2016-04-27 at 10 26 57 am" src="https://cloud.githubusercontent.com/assets/15234468/14855671/f35e1632-0c62-11e6-8507-e64064188f69.png">

**Comment by humancompanion** [comment]
* [ ] Fix the green outer focus on placeholders.
* [ ] Reduce margin between Searchable label and supporting text.
* [ ] Change "Add Resume" to "Upload or Build Resume", "Upload Document"

**Comment by lawrencek76** [comment]
Can we enumerate the reasons for including it?

**Comment by humancompanion** [comment]
@lawrencek76 - Of course. We learned from research that users wanted greater flexibility during the application process to manage their resumes and documents. Thus we have the ability to add documents in app guide to prevent users from having to leave the application, upload a doc, and then return. Given that we allow adding documents it is thus necessary to allow deleting given our limits around resumes (5) and documents (10). Users need to be able to delete a doc so that they can upload a new one if they hit their limit. 

My proposed solution to this problem and others related to managing documents is to relax the limits. The % of users hitting the limit is small. Increasing the limits would further decrease the number of folks who need to delete a doc in order to upload more. Disk is cheap. Let's buy more. But, I've not been able to convince anyone who could help make that a reality of that approach. Plus, it just delays the problem - we still need a solution.

Also, we know that users had problems in the past of uploading documents and not realizing that they were upside down, etc. Thus the intent of having thumbnails. If there was a thumbnail the user could see if there was a problem with their upload doc and correct it by deleting the doc and uploading it again. If we take away delete they won't be able to do that.

So we need delete. The question is: Why are some folks blowing past the text in the modal (besides the usual: users don't read those messages). 

The number of tickets dropped from 565 tickets from 01/19 - 02/19 to 372 tickets from 02/20 to 03/20 (app guide was released 02/20) under "Uploading Documents". Ticket counts in other categories also went down overall. It is a short range of time but, it's only been a short amount of time since application guide was released. The overall trend is downward but, that doesn't discount that this potentially a new sub-issue with the area of upload documents that should be addressed.

We've discussed a few solutions but, the most likely solution is to tighten up the modal to make it more clear that a resume is being deleted from their profile and not just from the application package. We'll probably include a checkbox that the user will have to check before they delete the doc permanently. We entertained the notion of a secondary action of "Remove from application" that just unselects that doc. But having two controls for the same action, selecting or unselecting a doc for inclusion, may just add to the confusion.

Follow on tasks:

* [ ] Create a new modal treatment for Deleting a document within application guide

**Comment by humancompanion** [comment]
The revised modal is here:
http://usajobs.github.io/design-system/modals/

It is the last of the three modals under the "Alert Variations" header. Comments welcome.

@kyhryt and I discussed adding some text along the lines of "I confirm I want to delete this document." and then requiring a checkbox to be checked before the "Delete Document" button would be enabled. I'm less keen on that now having just done the Delete Account modal where we don't have that behavior. It seems more appropriate for deleting an account than it does for deleting a document.

@dalenard21 - Can you check the language I used in both the Delete Document and Delete Account modals before than hand-off to Core Scrum team on Thursday? Thanks.

@kyhryt - We removed the top border on the footer (where the buttons are) of alerts. Do we want to do the same in modals? Please check other visual styling as well for these modals. Thanks.

**Comment by dalenard21** [comment]
@humancompanion 

Reviewed content.  Some minor edits.

## Delete Document Alert

If you delete this document, [Document Name], you will delete it from your account. You won’t be able to use this document for future job applications, unless you upload or build it again.

**If you delete this document, you can’t get it back.** 

### Want to keep the document, but not use it in your application?
If you want to keep the document, but don’t want to include it in your job application, then:
1.	Close this window.
2.	Click on the document to unselect it.
3.	Continue with your application.

## Delete Account Alert
If you delete your account, you will delete everything in your account, including your application history, resumes, saved searches, and all other documents. We do not save your information. 

**If you delete your account, you can’t undo it.** 

If you don’t want to delete your account, click **Cancel** or close the window.

**Comment by kyhryt** [comment]
@humancompanion @dalenard21 Looks and sound great! No feedback on my end. @humancompanion The top border of the button footer does show up in the mockup
