### ISSUE TITLE
Profile dashboard - improve keyboard accessibility

### ISSUE THREAD

**Issue by quadrinaquinn** [USAJOBS/design-system#74]
Allow the normal box shadow for links and buttons. Keyboard users are lost when tabbing. Recommend removing the following styles to allow default behavior - 

`.usajobs-home-saved-job__drawer-handle:focus {
  box-shadow: none;
}`

`button.usajobs-home-accordion-trigger:focus {
  box-shadow: none;
}`

`.usajobs-home-saved-job__drawer-handle:focus {
  box-shadow: none;
}`

**Comment by humancompanion** [comment]
Moved to https://github.com/USAJOBS/american-discovery-trail/issues/41
