### ISSUE TITLE
Modal Styling

### ISSUE THREAD

**Issue by kyhryt** [USAJOBS/design-system#9]
A few changes: 
- Can the modal body copy have the same left padding/margin as the Modal Header so that everything is aligned?
- Can the cancel button be a link instead of an actual button as shown in the mockup? 
- Can we change the color of the line dividers to a light grey or reduce the stroke so it's less heavy, as shown in the mockup? 

![pop-up-example](https://cloud.githubusercontent.com/assets/15234468/10642400/86397f30-77eb-11e5-97db-6a452dd0de73.png)

**Comment by kyhryt** [comment]
The header color should also be #112e51...Is the heading a h1 or h2? 

Ky!

**Comment by humancompanion** [comment]
Ky - I've already got an issue open for modals so I'm going to move your comments into that bug and answer them there.
